/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuotaRouteImport } from './routes/quota'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as HomeRouteImport } from './routes/home'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupSessionsRouteImport } from './routes/setup.sessions'
import { Route as SetupSafetyRouteImport } from './routes/setup.safety'
import { Route as SetupReadyRouteImport } from './routes/setup.ready'
import { Route as SetupQuotaRouteImport } from './routes/setup.quota'
import { Route as SetupNudgesRouteImport } from './routes/setup.nudges'
import { Route as SetupFloorRouteImport } from './routes/setup.floor'
import { Route as SetupExamRouteImport } from './routes/setup.exam'
import { Route as SetupClassRouteImport } from './routes/setup.class'

const QuotaRoute = QuotaRouteImport.update({
  id: '/quota',
  path: '/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSessionsRoute = SetupSessionsRouteImport.update({
  id: '/setup/sessions',
  path: '/setup/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSafetyRoute = SetupSafetyRouteImport.update({
  id: '/setup/safety',
  path: '/setup/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupReadyRoute = SetupReadyRouteImport.update({
  id: '/setup/ready',
  path: '/setup/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupQuotaRoute = SetupQuotaRouteImport.update({
  id: '/setup/quota',
  path: '/setup/quota',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupNudgesRoute = SetupNudgesRouteImport.update({
  id: '/setup/nudges',
  path: '/setup/nudges',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupFloorRoute = SetupFloorRouteImport.update({
  id: '/setup/floor',
  path: '/setup/floor',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupExamRoute = SetupExamRouteImport.update({
  id: '/setup/exam',
  path: '/setup/exam',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupClassRoute = SetupClassRouteImport.update({
  id: '/setup/class',
  path: '/setup/class',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/quota': typeof QuotaRoute
  '/setup/class': typeof SetupClassRoute
  '/setup/exam': typeof SetupExamRoute
  '/setup/floor': typeof SetupFloorRoute
  '/setup/nudges': typeof SetupNudgesRoute
  '/setup/quota': typeof SetupQuotaRoute
  '/setup/ready': typeof SetupReadyRoute
  '/setup/safety': typeof SetupSafetyRoute
  '/setup/sessions': typeof SetupSessionsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/quota': typeof QuotaRoute
  '/setup/class': typeof SetupClassRoute
  '/setup/exam': typeof SetupExamRoute
  '/setup/floor': typeof SetupFloorRoute
  '/setup/nudges': typeof SetupNudgesRoute
  '/setup/quota': typeof SetupQuotaRoute
  '/setup/ready': typeof SetupReadyRoute
  '/setup/safety': typeof SetupSafetyRoute
  '/setup/sessions': typeof SetupSessionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/profile': typeof ProfileRoute
  '/quota': typeof QuotaRoute
  '/setup/class': typeof SetupClassRoute
  '/setup/exam': typeof SetupExamRoute
  '/setup/floor': typeof SetupFloorRoute
  '/setup/nudges': typeof SetupNudgesRoute
  '/setup/quota': typeof SetupQuotaRoute
  '/setup/ready': typeof SetupReadyRoute
  '/setup/safety': typeof SetupSafetyRoute
  '/setup/sessions': typeof SetupSessionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/profile'
    | '/quota'
    | '/setup/class'
    | '/setup/exam'
    | '/setup/floor'
    | '/setup/nudges'
    | '/setup/quota'
    | '/setup/ready'
    | '/setup/safety'
    | '/setup/sessions'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/profile'
    | '/quota'
    | '/setup/class'
    | '/setup/exam'
    | '/setup/floor'
    | '/setup/nudges'
    | '/setup/quota'
    | '/setup/ready'
    | '/setup/safety'
    | '/setup/sessions'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/profile'
    | '/quota'
    | '/setup/class'
    | '/setup/exam'
    | '/setup/floor'
    | '/setup/nudges'
    | '/setup/quota'
    | '/setup/ready'
    | '/setup/safety'
    | '/setup/sessions'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  ProfileRoute: typeof ProfileRoute
  QuotaRoute: typeof QuotaRoute
  SetupClassRoute: typeof SetupClassRoute
  SetupExamRoute: typeof SetupExamRoute
  SetupFloorRoute: typeof SetupFloorRoute
  SetupNudgesRoute: typeof SetupNudgesRoute
  SetupQuotaRoute: typeof SetupQuotaRoute
  SetupReadyRoute: typeof SetupReadyRoute
  SetupSafetyRoute: typeof SetupSafetyRoute
  SetupSessionsRoute: typeof SetupSessionsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quota': {
      id: '/quota'
      path: '/quota'
      fullPath: '/quota'
      preLoaderRoute: typeof QuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/sessions': {
      id: '/setup/sessions'
      path: '/setup/sessions'
      fullPath: '/setup/sessions'
      preLoaderRoute: typeof SetupSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/safety': {
      id: '/setup/safety'
      path: '/setup/safety'
      fullPath: '/setup/safety'
      preLoaderRoute: typeof SetupSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/ready': {
      id: '/setup/ready'
      path: '/setup/ready'
      fullPath: '/setup/ready'
      preLoaderRoute: typeof SetupReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/quota': {
      id: '/setup/quota'
      path: '/setup/quota'
      fullPath: '/setup/quota'
      preLoaderRoute: typeof SetupQuotaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/nudges': {
      id: '/setup/nudges'
      path: '/setup/nudges'
      fullPath: '/setup/nudges'
      preLoaderRoute: typeof SetupNudgesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/floor': {
      id: '/setup/floor'
      path: '/setup/floor'
      fullPath: '/setup/floor'
      preLoaderRoute: typeof SetupFloorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/exam': {
      id: '/setup/exam'
      path: '/setup/exam'
      fullPath: '/setup/exam'
      preLoaderRoute: typeof SetupExamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/class': {
      id: '/setup/class'
      path: '/setup/class'
      fullPath: '/setup/class'
      preLoaderRoute: typeof SetupClassRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  ProfileRoute: ProfileRoute,
  QuotaRoute: QuotaRoute,
  SetupClassRoute: SetupClassRoute,
  SetupExamRoute: SetupExamRoute,
  SetupFloorRoute: SetupFloorRoute,
  SetupNudgesRoute: SetupNudgesRoute,
  SetupQuotaRoute: SetupQuotaRoute,
  SetupReadyRoute: SetupReadyRoute,
  SetupSafetyRoute: SetupSafetyRoute,
  SetupSessionsRoute: SetupSessionsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
